### PR TITLE
Replace "Test" with "Test::More"

### PR DESCRIPTION
**Pull request by JRaspass**
It'll provide better diagnostics on test failure.

Test::More was oddly already listed as a dependency despite this being the only test.

The test count went down by one because two tests were combined now that we have something more powerful than `ok`:
```diff
-ok( !defined( pop(@d) ) );
-ok( "@d", "2001 1 1 0 0 0" );
+is_deeply( \@d, [2001, 1, 1, 0, 0, 0, undef] );
```

### CODE REVIEW

**Review by oalders — APPROVED** [review]
Happy Hacktoberfest!

**Comment by JRaspass** [comment]
> Happy Hacktoberfest!

@oalders Speaking of which, mind slapping the "hacktoberfest" label on this PR (or repo, if you want more ;-)), it's showing as "Not Participating" on my dashboard :-(

**Comment by oalders** [comment]
I thought we had most of the repos covered. I've just added the tag now. Hopefully that syncs to your dashboard soon.

**Comment by JRaspass** [comment]
That worked, many thanks :+1:

**Pull request merged**
