### PR TITLE
Add test with Time::Zone

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Review by oalders — APPROVED** [review]
Thanks, @michal-josef-spacek!

**Comment by oalders** [comment]
@michal-josef-spacek could you add:

```    
    - Add test with Time::Zone (GH#25) (Michal Josef Špaček)
``` 

to `Changes` and force-push? That should get the tests firing.

**Comment by michal-josef-spacek** [comment]
@oalders Added, thanks :-)

**Comment by oalders** [comment]
Looks like this results in a 1.47% increase in coverage. 🥳 

https://app.codecov.io/gh/libwww-perl/HTTP-Date/commit/dea1427f9c9690208eddc3f1881383322c9881aa

**Pull request merged**
